# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Spending-Tracker' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Spending-Tracker
pod 'Charts'
pod 'Firebase/Auth'
pod 'Firebase/Firestore'
end
